[package]
name = "camt053"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }

[dependencies.chrono]
version = "0.4.20"
default-features = false
features = ["alloc", "std", "serde"]
