[package]
name = "kash_cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "kash"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
csv = "1.1.6"
tabular = "0.2.0"
colored = "2"
kash = { path = "../lib" }
