[package]
name = "kash_cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "kash"
path = "src/main.rs"

[dependencies]
tabular = "0.2.0"
colored = "2"
kash = { path = "../lib" }

[dependencies.clap]
version = "3.2.14"
default-features = false
features = ["std", "derive"]

[dependencies.kash_convert]
path = "../convert"
features = [
    "input-ktf",
    "input-json",
    "input-camt053",
    "output-json"
]
