[package]
name = "kash_convert"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
kash = { path = "../lib" }
