[package]
name = "ktf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.139", optional = true }
kash = { path = "../lib" }

[features]
default = ["serde"]
serde = ["dep:serde"]
