[package]
name = "kash_manage"
version = "0.1.0"
edition = "2021"

[dependencies]
kash = { path = "../lib" }
kash_convert = { path = "../convert" }

[features]
default = ["fs"]
fs = ["kash_convert/input-json"]
