[package]
name = "kash_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kash = { path = "../lib" }
kash_repo = { path = "../repo", default-features = false }
wasm-bindgen = "0.2.82"
